### ISSUE TITLE
bug - on spill over titles

### ISSUE THREAD

**Issue by wwe-johndpope** [uias/Tabman-Styles#1]
when the number of titles spills over width of title bar - the control can't scroll. 

check out XLPagerTabStrip for implementation sample
https://github.com/xmartlabs/XLPagerTabStrip

<img width="373" alt="screen shot 2017-03-28 at 4 33 51 pm" src="https://cloud.githubusercontent.com/assets/26149651/24426073/593e8260-13d4-11e7-92ae-650872f92f86.png">
```


eg.
  let okViewController = childViewController(withTitle: "This is a spill over test")

```
 func viewControllers(forPageboyViewController pageboyViewController: PageboyViewController) -> [UIViewController]? {
        let tweetsViewController = childViewController(withTitle: "Tweets")
        let repliesViewController = childViewController(withTitle: "Tweets & Replies")
        let mediaViewController = childViewController(withTitle: "Media")
        let likesViewController = childViewController(withTitle: "Likes")
        let okViewController = childViewController(withTitle: "This is a spill over test")
        let viewControllers = [tweetsViewController, repliesViewController, mediaViewController, likesViewController,okViewController]
        
        // create bar items
        var barItems = [TabmanBarItem]()
        for viewController in viewControllers {
            barItems.append(TabmanBarItem(title: viewController.pageTitle!.uppercased()))
        }
        
        self.bar.items = barItems
        return viewControllers
    }

```

**Comment by msaps** [comment]
Hi @wwe-johndpope, this behaviour is in fact intentional, the bar contents is scrollable but user scroll is disabled by default. 

Try setting `appearance.interaction.isScrollEnabled` to `true`. This will allow the bar to scroll independently of the page view controller contents (The bar will scroll with the page view controller index for info).

This raises a good point though, the default values should be better documented. I'll raise an issue in [Tabman](https://github.com/uias/Tabman) and get that sorted. 😄

**Comment by msaps** [comment]
Just for info, `.isScrollEnabled` is now set to `true` by default. This will be present from `v0.4.3`. See uias/Tabman#36

**Comment by wwe-johndpope** [comment]
nice thanks @msaps
